service: todo-with-ai
image: ghcr.io/soramameen/todo-with-ai

servers:
  - 45.32.45.18

proxy:
  app_port: 3000
  healthcheck:
    path: /up

registry:
  server: ghcr.io
  username: soramameen
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64
  context: .
  dockerfile: Dockerfile
