name: CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: Rubyのセットアップ
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ./todo_app/.ruby-version
          bundler-cache: true

      - name: DBのセットアップ
        working-directory: todo_app
        run: bin/rails db:create db:schema:load
        env:
          RAILS_ENV: test

      - name: RuboCop
        working-directory: todo_app
        run: bundle exec rubocop

      - name: RSpec
        working-directory: todo_app
        run: bundle exec rspec
        env:
          RAILS_ENV: test
